name: Acquire unity license

on:
  workflow_dispatch: {}

jobs:
  activation:
    runs-on: ubuntu-latest
    steps:
      - name: Request activation file
        id: getManualLicenseFile
        uses: game-ci/unity-request-activation-file@v2
        
      - name: Upload activation file in artifacts
        uses: actions/upload-artifact@v3
        with:
          name: UnityLicenseFile
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}