name: Build for WebGL and Deploy to Github Pages

on:
  push:
    branch: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build for WebGL
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-WebGL-${{ hashFiles('Packages/packages-lock.json') }}

      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL

      - uses: actions/upload-artifact@v3
        with:
          path: build/WebGL
          name: buildWebGL
  
  deploy:
    needs: build
    name: Deploy to Github Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          path: build
          name: buildWebGL

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build/WebGL
          ssh-key: ${{ secrets.DEPLOY_KEY }}